### ISSUE TITLE
🚀 Check downloaded files

### ISSUE THREAD

**Issue by MasterCruelty** [mariolzz/nyaa_boruto_downloader#8]
If the file's name of the episodes have a standard name, the script could check if you already downloaded the file before starting to open the webpage. What do you think?

**Comment by mariolzz** [comment]
Yes you could do that but that would mean that you can't move the downloaded files from the folder you download it into

**Comment by mariolzz** [comment]
No because you don't know what the latest episode is without opening the page

**Comment by MasterCruelty** [comment]
So you check after you open the page ok.
If you're already downloaded the latest episode, will it stop or it download again?
